name: video-english-recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pip:
    - openai-whisper
    - moviepy
    - opencv-python
    - torch
    - numpy
    - tqdm